language: cpp

os:
    - osx

before_install:
    - brew update
    - brew tap homebrew/science
    - brew tap sanelson/freecad
    - brew install eigen freetype qt homebrew/science/oce python boost-python pyside pyside-tools xerces-c orocos-kdl
    - brew install --without-framework --without-soqt sanelson/freecad/coin
    - brew install --HEAD pivy
    - pip install matplotlib==1.4.3
    - git clone https://github.com/Heeks/libarea.git ./libarea
    - pushd ./libarea && mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/ -DPYTHON_DIR=$(python-config --exec-prefix)/bin/ ../
    - make install
    - popd
    - brew unlink libspatialite
    - brew install libspatialite

install:
    - mkdir build && cd build && cmake -DFREECAD_USE_EXTERNAL_KDL=ON -DFREECAD_CREATE_MAC_APP=ON ../

script:
    - make -j2
    - bin/FreeCAD --run-test 0
    - bin/FreeCAD --log-file /tmp/FreeCAD.log &
    - sleep 10 && pkill FreeCAD
    - cat /tmp/FreeCAD.log
    - grep --file=../.log_errors /tmp/FreeCAD.log ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from build directory" || ( echo "Error from .log_errors found!" && false )
    - sudo make install/fast
    - /usr/local/FreeCAD.app/Contents/bin/FreeCAD --run-test 0
    - /usr/local/FreeCAD.app/Contents/bin/FreeCAD --log-file /tmp/FreeCAD_installed.log &
    - sleep 10 && pkill FreeCAD
    - cat /tmp/FreeCAD_installed.log
    - grep --file=../.log_errors /tmp/FreeCAD_installed.log ; [ $? == 1 ] && echo "No errors from .log_errors file found in the log after start from /usr/local/bin" || ( echo "Error from .log_errors found!" && false )

before_deploy:
    - cd /usr/local && zip -r -X FreeCAD_osx.zip FreeCAD.app -x FreeCAD.app/Contents/doc*

deploy:
    provider: releases
    api_key:
      secure: DXkMNaBJv6bYZbMTufrGQhZEiqsxipAEzjVlwtc0np2KTyrIq4iyWwSyDwNTHY4AplVAlo+1i8U/Amg1XQ0cV6tpWx1eYzJDNGUfq8haoLq5qhdZwVIpcQlCGQBPqDT79FQthVqsNMS4xRw0sbpPI6WiC80855IApk5DDQMUAc/h0zEuBXj609BL03w8iDVU4fKP4tJOOJKf8UunAOWYGVvaXs3smPHwRFqkkSrx/73MhaVy0l4XQj+fgCe69Zfz4GY+9Owk1abZNlwDFoMNNdSZf7tOEs/iDGQJl7VGDVl4kODeT5BYTB1WIGNR+a3eFFzv0BelZPfGlHykRddTTJoBvVuolF3EF6fQJ/ExNtusIXsb60Kwhlxi2NhtihQcGt0eorIntJUPvbHghUq7IN3uP73gB/kMcdIZhXKMqlfDnlHeEHTSx57tUSRUXXkUlT8cMzju7gS/lhZJdDeDJKtSKf0riFcBxecPEB6LB1W5LbsdPeaw+V5EJdiLfTKUFDzzWRo+gpVCZ2TBaVWnvym1nF+fQDWVxwbUece9nMMW7UYnHCo2dvFkrz7H0v8UE4OWWTG+9JEUCdwdCzNvJSUfAWs0N5sWqYLUDOcmyUTLBrOLomR3RoGK2v/2Re3kQzQoqLlTgr5wbQyx9qY3vkmBmlY/3ECEp44TtGuCdzQ= 
    file: "/usr/local/FreeCAD_osx.zip"
    on:
      tags: true
